version: '2'

services:
  velobike-labs:
    image: nginx:alpine
    container_name: velobike-labs
    restart: always
    volumes:
      - ./src:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - CERT_NAME="" # skip https
      - VIRTUAL_HOST=velobike-labs.urbica.co

networks:
  default:
    external:
      name: production-network
